=== MAkos42/BFNA2X_XMLGyak/BFNA2X_0928/MA_ertodtd.dtd
<!ELEMENT MAmodell (A+,B+,C,ABc+)>
<!ELEMENT A (Ab+,Ac)>
<!ATTLIST A Aa ID #REQUIRED>
<!ELEMENT Ab (Ax,Ay)>
<!ELEMENT Ax (#PCDATA)>
<!ELEMENT Ay (#PCDATA)>
<!ELEMENT Ac (Ad,Ae)>
<!ELEMENT Ad (#PCDATA)>
<!ELEMENT Ae (#PCDATA)>
<!ELEMENT B (Bb)>
<!ATTLIST B Ba ID #REQUIRED>
<!ELEMENT Bb (Bv,Bx)>
<!ELEMENT Bv (#PCDATA)>
<!ELEMENT Bx (#PCDATA)>
<!ELEMENT ABc (#PCDATA)>
<!ELEMENT C (Cb)>
<!ATTLIST C Ca ID #REQUIRED>
<!ELEMENT Cb (#PCDATA)>

=== MAkos42/BFNA2X_XMLGyak/BFNA2X_0928/MA_dtdtoxml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MAmodell SYSTEM "MA_ertodtd.dtd">
<MAmodell>
    <A Aa="id">
        <Ab>
            <Ax>idk</Ax>
            <Ay>teszt</Ay>
        </Ab>
        <Ab>
            <Ax>asd</Ax>
            <Ay>reeee</Ay>
        </Ab>
        <Ac>
            <Ad>ad</Ad>
            <Ae>sadasda</Ae>
        </Ac>
    </A>

    <B Ba="id2">
        <Bb>
            <Bv>dasd</Bv>
            <Bx>dasdas</Bx>
        </Bb>
    </B>
    <C Ca="asdas">
        <Cb>element</Cb>
    </C>
    <ABc>id to id2</ABc>
    
</MAmodell>
